export const with_honors = {
  json: {
    version: "5.2.1",
    objects: [
      {
        type: "image",
        version: "5.2.1",
        originX: "left",
        originY: "top",
        left: 0,
        top: 0,

        selectable: false,
        fill: "rgb(0,0,0)",
        stroke: null,
        strokeWidth: 0,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        lockMovementX: true,
        lockMovementY: true,
        skewX: 0,
        skewY: 0,
        cropX: 0,
        cropY: 0,
        id: "202342309954210000",
        name: "image",
        src: "./image/frame.png",
        crossOrigin: null,
        filters: [],
        perPixelTargetFind: true,
        // selectable: false,
        minWidth: 495,
      },
      {
        type: "textbox",
        version: "5.2.1",

        originX: "left",
        originY: "top",
        left: 8,
        top: 492.9,
        width: 483,
        height: 45.2,
        fill: "rgb(0,0,0)",
        stroke: null,
        strokeWidth: 1,
        lockMovementX: true,

        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        fontFamily: "Times New Roman",
        fontWeight: "normal",
        fontSize: 38,
        text: "Rivero, Dawn Andrew N.",
        hasControls: false,
        name: "textbox-name",
        underline: false,
        overline: false,
        linethrough: false,
        textAlign: "center",
        fontStyle: "normal",
        lineHeight: 1.16,
        textBackgroundColor: "",
        charSpacing: 0,
        styles: {},
        direction: "ltr",
        path: null,
        pathStartOffset: 0,
        pathSide: "left",
        pathAlign: "baseline",
        minWidth: 495,

        id: "2023423024711199357",
      },
      {
        type: "textbox",
        version: "5.2.1",

        originX: "left",
        originY: "top",
        left: 8,
        top: 547.9,
        width: 483,
        height: 45.2,
        fill: "rgb(0,0,0)",
        stroke: null,
        strokeWidth: 1,
        lockMovementX: true,

        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        fontFamily: "Times New Roman",
        fontWeight: "normal",
        fontSize: 46,
        text: "With Honors",
        name: "with-honors",
        hasControls: false,
        underline: false,
        overline: false,
        linethrough: false,
        textAlign: "center",
        fontStyle: "normal",
        lineHeight: 1.16,
        textBackgroundColor: "",
        charSpacing: 0,
        styles: {},
        direction: "ltr",
        path: null,
        pathStartOffset: 0,
        pathSide: "left",
        pathAlign: "baseline",
        minWidth: 495,

        id: "2023423024711199357",
      },
    ],
    background: "#fff",
  },
  size: { w: 500, h: 600 },
};
